/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IVRFMigratableConsumerV2Plus,
  IVRFMigratableConsumerV2PlusInterface,
} from "../IVRFMigratableConsumerV2Plus";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "vrfCoordinator",
        type: "address",
      },
    ],
    name: "CoordinatorSet",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "vrfCoordinator",
        type: "address",
      },
    ],
    name: "setCoordinator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IVRFMigratableConsumerV2Plus__factory {
  static readonly abi = _abi;
  static createInterface(): IVRFMigratableConsumerV2PlusInterface {
    return new utils.Interface(_abi) as IVRFMigratableConsumerV2PlusInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVRFMigratableConsumerV2Plus {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IVRFMigratableConsumerV2Plus;
  }
}
